name: Publish

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/_build.yml
    with:
      push: true
    secrets: inherit
